server:
  port: 9092

spring:
  application:
    name: cockroachdemo

  datasource:
    url: jdbc:postgresql://localhost:26257/gamesdb
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: caffeine
    cache-names:
      - gamesCache
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

management:
  endpoints:
    web:
      exposure.include: "health,prometheus"
      base-path: /
      path-mapping.prometheus: "metrics"
    jmx.exposure.exclude: "*"
  metrics:
    enable.jvm: true
    distribution:
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        "[http.server.requests]": "10ms,50ms,100ms,200ms,500ms,1s,5s,10s,30s"